export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_REGISTRATION = "GET_REGISTRATION";
export const REGISTRATION_LOADING = "REGISTRATION_LOADING";
export const REGISTRATION_NOT_FOUND = "REGISTRATION_NOT_FOUND";
export const CLEAR_CURRENT_REGISTRATION = "CLEAR_CURRENT_REGISTRATION";
export const GET_REGISTRATIONS = "GET_REGISTRATIONS";
